### PR TITLE
PMDK Support

### PR DESCRIPTION
**Pull request by hildebrandmw**
I've added PMDK as an external library requirement to make the contents of the library available within nGraph. Right now, these no CMake flag for enabling/disabling the use of the library, but that ... might be coming.

TODO
- [ ] Verify the PMDK library works correctly in nGraph.
- [ ] Add an option to `ngraph::malloc` to indicate if PMEM or normal memory is desired.
- [ ] Figure out how to pass the name of the persistent memory pool to `libngraph`. I think initially that this can be a fixed path, but that's definitely not a great permanent solution.
- [ ] Add a CMake option to enable/disable use of PMDK (probably low priority atm)

### CODE REVIEW

**Comment by powerjg** [comment]
I hope you know you're now going to be our resident cmake expert :)

**Comment by hildebrandmw** [comment]
Oh boy, we're in trouble ...

**Comment by hildebrandmw** [comment]
Some notes on the current (terrible) API so I don't forget

- Singleton type `ngraph::PoolManager`, contains a reference to the persistent memory pool being used. The type instance is acquired using `PoolManager::getinstance`
- The name of the pool can be set with `PoolManager::setpool` and the pmemobj create, open, and close functions are exposed as member functions of PoolManager
- By default, allocations are done to DRAM via the normal malloc. Allocation can be forced to PMEM using `PoolManager::enablepmem` (`PoolManager::disablepmem` ... disables that)
- A second boolean argument to `ngraph_malloc` can also be passed if the caller insists on using persistent memory
- The default build includes PMDK. You should be able to disable all the PMDK stuff by passing
`-DNGRAPH_PMDK_ENABLE=false` to cmake, but I haven't tested this (I also hate having `#ifdefs` everywhere, so I might yolo it an pull out this option ... we'll see.

Note that the `ngraph_malloc` function is not performance critical (I'm 80ish% sure memory is allocated in blocks and then managed by the runtime) so it's okay to throw a bunch of logic into that function.

**Comment by hildebrandmw** [comment]
Okay, I'm just leaving this PR as introducing PMDK into `nGraph` so `#include libpmemobj.h` can be used wherever it is needed. For now, I think libpmemobj is the way to go for allocating PMEM. However, since we're initially just using PMEM for extra storage, and not for the persistent aspect, a lot of the features of libpmemobj (i.e. transactions) are just not used.

**Comment by hildebrandmw** [comment]
It's also worth noting that if building with the `-DNGRAPH_PMDK_ENABLE` flag, the macro `NGRAPH_PMDK_ENABLE` will be available to the preprocessor for implementing `#ifdef` compile switches.

**Pull request merged**
